name: gym_app_alpha
description: A new Flutter project.
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  provider: ^6.0.0
  google_fonts: ^6.3.2
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.2.2
  http: ^1.5.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  flutter_stripe: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth_mocks: ^0.15.1
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
